# Generated by Django 2.2.5 on 2019-11-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccntInfo',
            fields=[
                ('accnt_num', models.IntegerField(db_column='accnt_num', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='user_name', max_length=45, null=True)),
                ('user_passwd', models.CharField(db_column='user_passwd', max_length=45, null=True)),
                ('bal', models.IntegerField(db_column='bal')),
                ('is_valid', models.IntegerField(db_column='is_valid')),
            ],
            options={
                'db_table': 'accnt_info',
                'managed': False,
            },
        ),
    ]
