# Generated by Django 2.2.5 on 2019-11-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('staff_id', models.CharField(db_column='staff_id', max_length=45, primary_key=True, serialize=False)),
                ('staff_passwd', models.CharField(db_column='staff_passwd', max_length=45)),
            ],
            options={
                'db_table': 'staff_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransInfo',
            fields=[
                ('trans_num', models.IntegerField(db_column='trans_num', primary_key=True, serialize=False)),
                ('source_accnt', models.IntegerField(db_column='source_accnt')),
                ('dest_accnt', models.IntegerField(db_column='dest_accnt')),
                ('amnt', models.IntegerField(db_column='amnt')),
            ],
            options={
                'db_table': 'trans_info',
                'managed': False,
            },
        ),
    ]
